/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei/native";
import { Asset } from "expo-asset";
import React, { useRef } from "react";

const assetName = require("./Llama.glb");

export default function Llama(props: any) {
  const group = useRef(null);
  const { nodes, materials } = useGLTF(Asset.fromModule(assetName).uri);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="AnimalArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
          <group name="Llama" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh
              name="Llama_1"
              geometry={nodes.Llama_1.geometry}
              material={materials.Main}
              skeleton={nodes.Llama_1.skeleton}
            />
            <skinnedMesh
              name="Llama_2"
              geometry={nodes.Llama_2.geometry}
              material={materials.Hair}
              skeleton={nodes.Llama_2.skeleton}
            />
            <skinnedMesh
              name="Llama_3"
              geometry={nodes.Llama_3.geometry}
              material={materials.Main_Dark}
              skeleton={nodes.Llama_3.skeleton}
            />
            <skinnedMesh
              name="Llama_4"
              geometry={nodes.Llama_4.geometry}
              material={materials.Muzzle}
              skeleton={nodes.Llama_4.skeleton}
            />
            <skinnedMesh
              name="Llama_5"
              geometry={nodes.Llama_5.geometry}
              material={materials.Hooves}
              skeleton={nodes.Llama_5.skeleton}
            />
            <skinnedMesh
              name="Llama_6"
              geometry={nodes.Llama_6.geometry}
              material={materials.Main_Light}
              skeleton={nodes.Llama_6.skeleton}
            />
            <skinnedMesh
              name="Llama_7"
              geometry={nodes.Llama_7.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Llama_7.skeleton}
            />
            <skinnedMesh
              name="Llama_8"
              geometry={nodes.Llama_8.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Llama_8.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
